const ADD_USER = "ADD_USER";
const UPDATE_USER = "UPDATE_USER";
const DELETE_USER = "DELETE_USER";
const EDIT_USER = "EDIT_USER";
const CANCEL_EDIT_USER = "CANCEL_EDIT_USER";

export default {
  ADD_USER,
  UPDATE_USER,
  DELETE_USER,
  EDIT_USER,
  CANCEL_EDIT_USER
};
